# Generated by Django 5.0 on 2024-06-04 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('empnum', models.AutoField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmpAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50)),
                ('numofdays', models.IntegerField()),
                ('empnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.emp')),
            ],
        ),
        migrations.CreateModel(
            name='EmpBasicPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basicpay', models.FloatField()),
                ('empnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.emp')),
            ],
        ),
        migrations.CreateModel(
            name='EmpTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_tax', models.IntegerField()),
                ('empnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.emp')),
            ],
        ),
    ]
